baseurl: "/"
title: "Statistical Programming"
author: "Colin Rundel"
copyright: "&copy; 2020. All rights reserved."
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir: "docs"

menu:
  main:
  - name: Home
    pre: <i class='fa fa-home fa-fw'></i>
    weight: 1
    identifier: home
    url: "#schedule"  
  - name: Syllabus
    pre: <i class='fa fa-file-text-o fa-fw'></i>
    weight: 2
    identifier: syllabus
    url: "#syllabus"
  - name: Piazza
    pre: <i class="fas fa-comment fa-fw"></i>
    weight: 3
    url: http://piazza.com/ed.ac.uk/fall2019/math11176
  - name: Github
    pre: <i class='fa fa-github fa-fw'></i>
    weight: 6
    url: https://github.com/statprog-s1-2020
  - name: RStudio
    pre: <i class='fab fa-r-project fa-fw'></i>
    weight: 7
    url: https://noteable.edina.ac.uk/login

params:
  subtitle: "(2020-2021) [Sem 1]"
  course: "Math 11176"
  highlightjs: androidstudio
  highlightjs_extra_languages:
    - yaml
  dateFormat: '02 Jan 2006, 15:04'
  sections:
    - schedule
    - syllabus
    - textbooks
    - contact
    - about
  contact:
    - name: Dr. Colin Rundel
      office: 2256 JCMB
      email: colin.rundel@ed.ac.uk
      hours: TBD
    - name: Dr. Simon Wood
      office: 
      email: simon.wood@ed.ac.uk
      hours: TBD
  assignments:
    - name: Homework 0
      type: Individual
      value: Not marked
      out: Week 1
    - name: Homework 1
      type: Team
      value: TBD
      out: Week 2
    - name: Homework 2
      type: Team
      value: TBD
      out: Week 4
    - name: Project 1
      type: Individual
      value: TBD
      out: Week 5
    - name: Homework 3
      type: Team
      value: TBD
      out: Week 7
    - name: Homework 4
      type: Team
      value: TBD
      out: Week 9
    - name: Project 2
      type: Individual
      value: TBD
      out: Week 10